name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-dockerize:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build: true
          tag: naren-docker-image-name:latest

           - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA5CA4RZCYEXJDJO7U
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: Push Docker image to AWS ECR
  run: |
    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 897708050608.dkr.ecr.ap-south-1.amazonaws.com
    docker push 897708050608.dkr.ecr.ap-south-1.amazonaws.com/naren-docker-image-name:latest
