name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:

  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run:  docker build . --file Dockerfile --tag naren:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'naren:latest'  # Referencing the locally built Docker image
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  push-to-ecr:
    runs-on: ubuntu-latest

    needs: build-and-scan  # Wait for build-and-scan job to complete before starting this job

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 897708050608.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push Docker image to Amazon ECR
        run: docker push 897708050608.dkr.ecr.ap-south-1.amazonaws.com/sampleproject_githubactions:latest
