name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-to-ecr:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    # Install Anchore Engine
    - name: Install Anchore Engine
      run: docker pull docker.io/anchore/anchore-engine:v0.10.0

    # Start Anchore Engine container
    - name: Start Anchore Engine container
      run: docker run -d --name anchore_engine docker.io/anchore/anchore-engine:v0.10.0

    # Wait for Anchore Engine to start
    - name: Wait for Anchore Engine to start
      run: |
        until docker exec anchore_engine anchore-cli system status >/dev/null 2>&1; do
          echo "Waiting for Anchore Engine to start..."
          sleep 5
        done

    # Scan Docker image with Anchore Engine
    - name: Scan D
